#!/bin/bash

#SBATCH -p gpu --gres=gpu:1
#SBATCH -t 12:00:00
#SBATCH --mem=64G
#SBATCH -n 2
#SBATCH -C geforce3090

module load cuda/11.1.1
python ../v3/train.py --expt-name mar03_armadillo_standard --input-dir /gpfs/data/ssrinath/neural-odf/data/common-3d-test-models/rendered-data-5d/ --dataset armadillo --output-dir /gpfs/data/ssrinath/neural-odf/output/ --arch standard --epochs 500 -s 42 --rays-per-shape 1000

