#!/bin/bash

#SBATCH -p gpu --gres=gpu:1
#SBATCH -t 72:00:00
#SBATCH --mem=64G
#SBATCH -n 2
#SBATCH -C geforce3090

module load cuda/11.1.1
python ../v2/train.py --expt-name feb17_torus_constant_NoInt1_weights_5_5_1_1 --input-dir /gpfs/data/ssrinath/neural-odf/data/common-3d-test-models/rendered-data-5d/ --output-dir /gpfs/data/ssrinath/neural-odf/output/ --arch constant --epochs 500 --no-posenc -s 42 --rays-per-shape 1000
